version: "5.0.4"

networks:
   frontend:
   backend:

services:
   catalog:
      build:
         context: .\src\Services\ProductCatalogApi
         dockerfile: Dockerfile
      image: shoes/catalog
      environment:
         - DatabaseServer=mssqlserver
         - DatabaseName=CatalogDb
         - DatabaseUser=sa
         - DatabasePassword=ProductApi(!)
         - ASPNETCORE_URLS=http://+:5004
         - ASPNETCORE_ENVIRONMENT=Production
      container_name: catalogapi
      ports:
         - "5004:5004"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver
         
   mssqlserver:
      image: "mcr.microsoft.com/mssql/server:2019-latest"
      ports:
         - "1445:1433"

      container_name: mssqlcontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=ProductApi(!)
         - MSSQL_PID=Developer
      networks:
         - backend

      

